### ISSUE TITLE
radius on corners of the bootstrap navbar

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/agile-ventures-website-react-front-end#1]
little bits of white background appearing:

![](https://dl.dropbox.com/s/2fv8qnmvzt77cgh/Screenshot%202018-03-09%2011.14.27.png?dl=0)

**Comment by mattwr18** [comment]
we have gone with semantic-ui to be a little different since bootstrap has become so popular. I think this issue can be closed @tansaku @Joseph @FedericoEsparza
