### ISSUE TITLE
Add columns and labels to new Waffle Board

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/agile-ventures-website-react-front-end#26]
Add columns and labels to new Waffle Board

https://waffle.io/AgileVentures/agile-ventures-website-react-front-end

**Comment by FedericoEsparza** [comment]
@Kachulio1 Can you review, please: https://waffle.io/AgileVentures/agile-ventures-website-react-front-end
https://github.com/AgileVentures/agile-ventures-website-react-front-end/labels
 
You'll need to manually move the issue to `Done` if Approved, since no PR is required.

**Comment by Kachulio1** [comment]
cool
