### ISSUE TITLE
Setup default branches

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/agile-ventures-website-react-front-end#30]
Setup default branches
 - `develop` `staging` and `production`? or clean `master`?

**Comment by FedericoEsparza** [comment]
@tansaku Could you also give @Kachulio1 admin access, so he can review this ticket?
Can't create a PR for this one.

Protected `develop` `staging` and `master`
 
Here's a video of my working on it: http://youtu.be/RnTG9WCbQcc

Move to `DONE` if approved

**Comment by tansaku** [comment]
@FedericoEsparza have given @Kachulio1 admin access

I think `develop` `staging` and `master` is a good pattern, particularly since that will mirror the WSO backend

**Comment by FedericoEsparza** [comment]
Thanks, @tansaku 
Agreed.

And to be clear, `develop` is the default and is now protected. `staging` and `master` are also now protected.
