### ISSUE TITLE
Integrate travis & wafflebot

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/agile-ventures-website-react-front-end#31]
Integrate travis & wafflebot

**Comment by FedericoEsparza** [comment]
Integrating travis was done by:
1) navigating here: 
https://travis-ci.org/organizations/AgileVentures/repositories 
2) locating the repo
3) toggling the button to green
![Screen Shot 2018-12-10 at 8.06.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e387b76082a50f00d31003/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f36b7191a370f1122d4f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ebed1385a21c56911afbb8b18b601ba298e4cd7b0be881ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df24fe54451a4163261ee7f2431.png)

**Comment by FedericoEsparza** [comment]
@tansaku Only an organization owner can install wafflebot https://help.waffle.io/wafflebot-basics/getting-started-with-the-wafflebot/how-do-i-install-wafflebot
 
Could you please install it for this repo?

**Comment by tansaku** [comment]
@FedericoEsparza I think I've done it - let me know if it's not working properly ...

**Comment by FedericoEsparza** [comment]
Thanks, @tansaku 
We'll try it out today.
