### ISSUE TITLE
Add standardjs

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/agile-ventures-website-react-front-end#34]
Add `standardjs`
Sets up linters, style guide, and formatter
 
@dkuku suggested it, and I'm all for trying it, as it purports to just work, without configuring linter files.
 
Follow instructions here: https://standardjs.com/
 
But it's basically just an npm dev dependency, so  install with:
  
```npm install standard --save-dev```
 
I think we might want to avoid making the actual formatting changes, and save that for a separate ticket after it's prepended to the test script in `package.json`, a la: ```standard && react-scripts test --env=jsdom```
Especially since we first want to carve out the actual code that we want to use (I'm working on it). Otherwise this PR will end up being huge.

**Comment by mattwr18** [comment]
@aonomike said he will work on this
